// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/proto/magnitude.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,4,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`                        // l2, cosine, dot, manhattan
	IndexType     string                 `protobuf:"bytes,6,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"` // flat, ivf, hnsw, spann
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCollectionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CreateCollectionRequest) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

type CollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,3,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,6,opt,name=metric,proto3" json:"metric,omitempty"`
	IndexType     string                 `protobuf:"bytes,7,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VectorCount   int32                  `protobuf:"varint,9,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionResponse) Reset() {
	*x = CollectionResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionResponse) ProtoMessage() {}

func (x *CollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionResponse.ProtoReflect.Descriptor instead.
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CollectionResponse) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *CollectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CollectionResponse) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *CollectionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CollectionResponse) GetVectorCount() int32 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCollectionsRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionResponse  `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionResponse {
	if x != nil {
		return x.Collections
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteCollectionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *DeleteCollectionRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       string                 `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Ids           []uint64               `protobuf:"varint,4,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Vectors       []*FloatVector         `protobuf:"bytes,5,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Metadata      [][]byte               `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty"` // JSON-encoded metadata per vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{8}
}

func (x *InsertRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InsertRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *InsertRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *InsertRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *InsertRequest) GetVectors() []*FloatVector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *InsertRequest) GetMetadata() [][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FloatVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatVector) Reset() {
	*x = FloatVector{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatVector) ProtoMessage() {}

func (x *FloatVector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatVector.ProtoReflect.Descriptor instead.
func (*FloatVector) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{9}
}

func (x *FloatVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{10}
}

func (x *InsertResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Query         []float32              `protobuf:"fixed32,4,rep,packed,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,5,opt,name=k,proto3" json:"k,omitempty"`
	Nprobe        int32                  `protobuf:"varint,6,opt,name=nprobe,proto3" json:"nprobe,omitempty"`
	Filter        []byte                 `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"` // JSON-encoded filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *SearchRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetNprobe() int32 {
	if x != nil {
		return x.Nprobe
	}
	return 0
}

func (x *SearchRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Ids           []uint64               `protobuf:"varint,4,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorRequest) Reset() {
	*x = DeleteVectorRequest{}
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorRequest) ProtoMessage() {}

func (x *DeleteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_magnitude_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_magnitude_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVectorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteVectorRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *DeleteVectorRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *DeleteVectorRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_internal_grpc_proto_magnitude_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_magnitude_proto_rawDesc = "" +
	"\n" +
	"#internal/grpc/proto/magnitude.proto\x12\tmagnitude\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc0\x01\n" +
	"\x17CreateCollectionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x04 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metric\x12\x1d\n" +
	"\n" +
	"index_type\x18\x06 \x01(\tR\tindexType\"\x8d\x02\n" +
	"\x12CollectionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x03 \x01(\tR\n" +
	"databaseId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x05 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06metric\x18\x06 \x01(\tR\x06metric\x12\x1d\n" +
	"\n" +
	"index_type\x18\a \x01(\tR\tindexType\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12!\n" +
	"\fvector_count\x18\t \x01(\x05R\vvectorCount\"V\n" +
	"\x16ListCollectionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\"Z\n" +
	"\x17ListCollectionsResponse\x12?\n" +
	"\vcollections\x18\x01 \x03(\v2\x1d.magnitude.CollectionResponseR\vcollections\"|\n" +
	"\x17DeleteCollectionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\tR\adeleted\"\xd2\x01\n" +
	"\rInsertRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\x04R\x03ids\x120\n" +
	"\avectors\x18\x05 \x03(\v2\x16.magnitude.FloatVectorR\avectors\x12\x1a\n" +
	"\bmetadata\x18\x06 \x03(\fR\bmetadata\"%\n" +
	"\vFloatVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\",\n" +
	"\x0eInsertResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\"\xc6\x01\n" +
	"\rSearchRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x12\x14\n" +
	"\x05query\x18\x04 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x05 \x01(\x05R\x01k\x12\x16\n" +
	"\x06nprobe\x18\x06 \x01(\x05R\x06nprobe\x12\x16\n" +
	"\x06filter\x18\a \x01(\fR\x06filter\"l\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"C\n" +
	"\x0eSearchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.magnitude.SearchResultR\aresults\"\x8a\x01\n" +
	"\x13DeleteVectorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\x04R\x03ids2\x9f\x04\n" +
	"\x10MagnitudeService\x12=\n" +
	"\x06Health\x12\x18.magnitude.HealthRequest\x1a\x19.magnitude.HealthResponse\x12U\n" +
	"\x10CreateCollection\x12\".magnitude.CreateCollectionRequest\x1a\x1d.magnitude.CollectionResponse\x12X\n" +
	"\x0fListCollections\x12!.magnitude.ListCollectionsRequest\x1a\".magnitude.ListCollectionsResponse\x12Q\n" +
	"\x10DeleteCollection\x12\".magnitude.DeleteCollectionRequest\x1a\x19.magnitude.DeleteResponse\x12=\n" +
	"\x06Insert\x12\x18.magnitude.InsertRequest\x1a\x19.magnitude.InsertResponse\x12=\n" +
	"\x06Search\x12\x18.magnitude.SearchRequest\x1a\x19.magnitude.SearchResponse\x12J\n" +
	"\rDeleteVectors\x12\x1e.magnitude.DeleteVectorRequest\x1a\x19.magnitude.DeleteResponseB5Z3github.com/POTATO-VE1/Magnitude/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_magnitude_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_magnitude_proto_rawDescData []byte
)

func file_internal_grpc_proto_magnitude_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_magnitude_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_magnitude_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_magnitude_proto_rawDesc), len(file_internal_grpc_proto_magnitude_proto_rawDesc)))
	})
	return file_internal_grpc_proto_magnitude_proto_rawDescData
}

var file_internal_grpc_proto_magnitude_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_grpc_proto_magnitude_proto_goTypes = []any{
	(*HealthRequest)(nil),           // 0: magnitude.HealthRequest
	(*HealthResponse)(nil),          // 1: magnitude.HealthResponse
	(*CreateCollectionRequest)(nil), // 2: magnitude.CreateCollectionRequest
	(*CollectionResponse)(nil),      // 3: magnitude.CollectionResponse
	(*ListCollectionsRequest)(nil),  // 4: magnitude.ListCollectionsRequest
	(*ListCollectionsResponse)(nil), // 5: magnitude.ListCollectionsResponse
	(*DeleteCollectionRequest)(nil), // 6: magnitude.DeleteCollectionRequest
	(*DeleteResponse)(nil),          // 7: magnitude.DeleteResponse
	(*InsertRequest)(nil),           // 8: magnitude.InsertRequest
	(*FloatVector)(nil),             // 9: magnitude.FloatVector
	(*InsertResponse)(nil),          // 10: magnitude.InsertResponse
	(*SearchRequest)(nil),           // 11: magnitude.SearchRequest
	(*SearchResult)(nil),            // 12: magnitude.SearchResult
	(*SearchResponse)(nil),          // 13: magnitude.SearchResponse
	(*DeleteVectorRequest)(nil),     // 14: magnitude.DeleteVectorRequest
}
var file_internal_grpc_proto_magnitude_proto_depIdxs = []int32{
	3,  // 0: magnitude.ListCollectionsResponse.collections:type_name -> magnitude.CollectionResponse
	9,  // 1: magnitude.InsertRequest.vectors:type_name -> magnitude.FloatVector
	12, // 2: magnitude.SearchResponse.results:type_name -> magnitude.SearchResult
	0,  // 3: magnitude.MagnitudeService.Health:input_type -> magnitude.HealthRequest
	2,  // 4: magnitude.MagnitudeService.CreateCollection:input_type -> magnitude.CreateCollectionRequest
	4,  // 5: magnitude.MagnitudeService.ListCollections:input_type -> magnitude.ListCollectionsRequest
	6,  // 6: magnitude.MagnitudeService.DeleteCollection:input_type -> magnitude.DeleteCollectionRequest
	8,  // 7: magnitude.MagnitudeService.Insert:input_type -> magnitude.InsertRequest
	11, // 8: magnitude.MagnitudeService.Search:input_type -> magnitude.SearchRequest
	14, // 9: magnitude.MagnitudeService.DeleteVectors:input_type -> magnitude.DeleteVectorRequest
	1,  // 10: magnitude.MagnitudeService.Health:output_type -> magnitude.HealthResponse
	3,  // 11: magnitude.MagnitudeService.CreateCollection:output_type -> magnitude.CollectionResponse
	5,  // 12: magnitude.MagnitudeService.ListCollections:output_type -> magnitude.ListCollectionsResponse
	7,  // 13: magnitude.MagnitudeService.DeleteCollection:output_type -> magnitude.DeleteResponse
	10, // 14: magnitude.MagnitudeService.Insert:output_type -> magnitude.InsertResponse
	13, // 15: magnitude.MagnitudeService.Search:output_type -> magnitude.SearchResponse
	7,  // 16: magnitude.MagnitudeService.DeleteVectors:output_type -> magnitude.DeleteResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_magnitude_proto_init() }
func file_internal_grpc_proto_magnitude_proto_init() {
	if File_internal_grpc_proto_magnitude_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_magnitude_proto_rawDesc), len(file_internal_grpc_proto_magnitude_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_magnitude_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_magnitude_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_magnitude_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_magnitude_proto = out.File
	file_internal_grpc_proto_magnitude_proto_goTypes = nil
	file_internal_grpc_proto_magnitude_proto_depIdxs = nil
}
